const Images = {
    splashImage: require('./images/splashImage.jpg'),
    account:require('./images/account.png'),
    menu:require('./images/menu.png'),
    homeicon:require('./images/homeicon.png'),
    favourites:require('./images/favourites.png'),
    accountSelected:require('./images/accountSel.png'),
    menuSelected:require('./images/menuSelected.png'),
    star:require('./images/star.png'),
    home3:require('./images/home.png'),
    add:require('./images/add.png'),
    search:require('./images/search.png'),
    nochat : require('./images/nochat.png'),
    oneModal: require('./images/oneModal.png'),
    twoModal: require('./images/twoModal.png'),
    threeModal: require('./images/threeModal.png'),
    backArrow:require('./images/backArrow.png'),
    dots: require('./images/dots.png'),
    paperPlane: require('./images/paper-plane.png'),
    notfound:require('./images/noResultFoundText.png'),
    delete:require('./images/delete.png'),
    eye:require('./images/Glyph.png'),
    call: require('./images/call.png'),
    user: require('./images/profile-user.png'),
    message: require('./images/comment.png'),
    email: require('./images/email.png'),

}
export default Images;